In [1]:
import pandas as pd

students_performance2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/prework_data/main/students_performance.csv")

students_performance2.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
students_performance2.shape

(1000, 8)

In [3]:
students_performance2.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [7]:
students_performance2.gender.unique()

array(['female', 'male'], dtype=object)

In [17]:
students_performance2["race/ethnicity"].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [18]:
students_performance2["parental level of education"].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [19]:
students_performance2.lunch.unique()

array(['standard', 'free/reduced'], dtype=object)

In [20]:
students_performance2["test preparation course"].unique()

array(['none', 'completed'], dtype=object)

In [23]:
numerical_variables = ["math score","reading score","writing score"]

In [24]:
students_performance2[numerical_variables].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [25]:
students_performance2[numerical_variables].mode()

   math score  reading score  writing score
0          65             72             74

In [26]:
students_performance2[numerical_variables].median()

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [28]:
students_performance2[numerical_variables].describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [29]:
students_performance2[numerical_variables].std()

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [30]:
students_performance2[numerical_variables].max() - students_performance2[numerical_variables].min()

math score       100
reading score     83
writing score     90
dtype: int64

In [31]:
categorical_variables = ["gender","race/ethnicity","parental level of education","lunch","test preparation course"]

In [33]:
students_performance2[categorical_variables].value_counts()

gender  race/ethnicity  parental level of education  lunch         test preparation course
female  group C         associate's degree           standard      none                       21
                        some college                 standard      none                       19
male    group C         high school                  standard      none                       17
female  group C         associate's degree           standard      completed                  15
                        high school                  standard      none                       15
                                                                                              ..
        group D         master's degree              free/reduced  none                        1
                        bachelor's degree            free/reduced  completed                   1
        group C         master's degree              standard      none                        1
                                                     free/reduced  completed                   1
        group E         some high school             standard      none                        1
Name: count, Length: 211, dtype: int64

In [36]:
for column in categorical_variables:
    print (students_performance2[column].value_counts())

gender
female    518
male      482
Name: count, dtype: int64
race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
lunch
standard        645
free/reduced    355
Name: count, dtype: int64
test preparation course
none         642
completed    358
Name: count, dtype: int64